### PR TITLE
Add slackUsernameFormat config option

### LINKED ISSUE #56: Allow customization of Slack/IRC username format
Right now everything is posted to Slack with the username of the IRC message author. This sometimes causes confusion from people that doesn't know where the messages are coming from, especially in large channels.

An option could be adding a `slackUsernameFormat` config option with username interpolation, so for example `$username (IRC)` would result in messages being posted by `ekmartin (IRC)` instead of just `ekmartin`. Could also have an `ircUsernameFormat` which would default to `<$username>`, which would allow stuff like #19.

Another option would of course just be to change the default representation from just username to something suffixed with `(sent from IRC)` or similar. The less config options the better, however as this would be a breaking change with little flexibility I'm not sure.

Any feedback is welcome.

### PR DESCRIPTION
**Pull request by laughinghan**
Close #56

### CODE REVIEW

**Comment by laughinghan** [comment]
@ekmartin: lol did you add Coveralls twice or something

**Comment by ekmartin** [comment]
Brilliant! I agree with what you said in https://github.com/ekmartin/slack-irc/issues/56#issuecomment-258967286 - let's go with `$username (IRC)` as the default. Whether it's a breaking change or not is up for discussion, but I think it's fine to just do it in a minor version bump, since as you said - it's a cosmetic change.

Should this maybe be nested under an object, to make it cleaner to add support for IRC username formatting as well? 

```json
"usernameFormat": {
   "slack": "$username (IRC)",
   "irc": "<$username>"
}
```

Or do you think it's clearer with just `slackUsernameFormat` and `ircUsernameFormat`?

**Comment by laughinghan** [comment]
Great! Will do.

I don't think it should be nested, but I also see no use for `ircUsernameFormat` since messages in IRC from the bot (piped from Slack) are already distinguished by coming from the bot, much moreso than bot messages in Slack.

**Comment by ekmartin** [comment]
I think one use case would be if people for some reason would want to remove the username when messages are posted to IRC. Might be good to have both just for unity, but we can merge this and look at it later.

**Comment by laughinghan** [comment]
@ekmartin: eh yeah let's just deal with that later. Updated default Slack username format.

**Comment by ekmartin** [comment]
Great, thanks! I'll create a release later.

**Comment by ekmartin** [comment]
Released in [3.9.0](https://github.com/ekmartin/slack-irc/blob/master/CHANGELOG.md#390---2016-11-07) - thanks again!

**Pull request merged**
