### PR TITLE
Adds support for IRC-Actions

### PR DESCRIPTION
**Pull request by heiglandreas**
This commit adds a way to support action-messages from IRC

### CODE REVIEW

**Comment by ekmartin** [comment]
Sorry for the late answer. This should probably just be a tiny wrapper around `sendToSlack` that formats it as a message and calls the function. That way we would avoid a lot of duplicate code. Also, with the current code this'll send all messages twice to Slack, as a regular message also fires `raw` events.

**Comment by heiglandreas** [comment]
Sorry for taking a while. I've rewritten the method to call the ```sendToSlack``` function which is much more convenient. Additionally I've integrated the last-minute-change I've added to my wortking copy that avoided sending messages twice :wink:

**Comment by ekmartin** [comment]
After checking a bit it seems like `node-irc` actually emits an `action`-event which could be used instead (https://github.com/martynsmith/node-irc/blob/master/lib/irc.js#L1018). Just seems like it isn't in the documentation. 

The arguments passed to the event listener are:
* Username
* Channel
* Message
* Raw object

Maybe we should format the message sent to Slack a bit too, for example by posting it in italic? I.e., _ekmartin runs_.

**Comment by heiglandreas** [comment]
I'll habe a look at that action-event-listener! And the formatting might come from that then. Using ```/me``` works in slack as it does in IRC, so I'd use that one for formatting.

**Comment by ekmartin** [comment]
Cool :+1:

**Comment by ekmartin** [comment]
Would be cool to support `/me`s from Slack to IRC too. The message object looks like this:
```js
{ 
  text: 'this is the message',
  type: 'message',
  subtype: 'me_message',
  user: 'U02HAE2MM',
  channel: 'C03JSFQT3',
  ts: '1433094875.000007' 
}
```

They're currently ignored [here](https://github.com/ekmartin/slack-irc/blob/master/lib%2Fbot.js#L82) because the message object contains a subtype.

**Comment by RX14** [comment]
Any chance of getting this merged?

**Comment by heiglandreas** [comment]
I've got to do some more work on that. Might take a week or so.

I'll do my best to get it fixed soon

**Comment by RX14** [comment]
thanks

**Comment by ekmartin** [comment]
Any update regarding this @heiglandreas? If you don't have time I'll fix it, no problem.

**Comment by heiglandreas** [comment]
Sorry, not really! If you've got time feel free to go for it! I've got far to much around my head at the moment :frowning:

**Comment by ekmartin** [comment]
No problem! Closing this for now then.

**Pull request closed without merging**
