### PR TITLE
Updated IRC support

### PR DESCRIPTION
**Pull request by robertkety**
Added support for join, part, quit, and notices. Also added a bot welcome message configurable in config.json.  Also fixed indentation issues for CI (hopefully!)

### CODE REVIEW

**Comment by robertkety** [comment]
Sorry for all the formatting commits.  Silly white space and quotation mark dependencies...

**Comment by ekmartin** [comment]
Do you have time to make a new pull request with just the notice support? For people that use slack-irc with IRC channels that have 500+ members showing all join/parts would be quite spammy. Could be an option to make it possible to enable it with a config option, but that discussion should probably be in its own pull request.

As for the welcome messages, I really don't think that's something that belongs in slack-irc (there's plenty of IRC bots that can handle this much better).

We should also have a test for notice support, similar to [this one](https://github.com/ekmartin/slack-irc/blob/master/test/bot-events.test.js#L63).

**Comment by robertkety** [comment]
Sorry! I haven't had time to work on this.  I'll open a new request when I find time.

**Comment by ekmartin** [comment]
No problem, thank you :)

**Pull request closed without merging**
