### PR TITLE
Env Var support for SLACK_TOKEN

### PR DESCRIPTION
**Pull request by javajax**
Add support for "SLACK_TOKEN" as an environment variable.
example:

```
slack-irc --config config.json SLACK_TOKEN=qwerkjlasdaviua
```

### CODE REVIEW

**Comment by ekmartin** [comment]
May I ask why you need this? Configuring with environment variables is cool, but since you'd still require a config for the channel mapping I don't see the point of having the possibility of providing only the token as an environment variable?

**Comment by javajax** [comment]
We want to be able to have the configuration under source control but keep all the sensitive data out of the repo.  we are using heroku so the env configuration is the most accessible but having the sensitive data configurable by env variables seems like a good feature.

**Comment by ekmartin** [comment]
Hm, I see. I wrote a comment about Heroku and env variables a while back, here: https://github.com/ekmartin/slack-irc/issues/12#issuecomment-84958867

I'm not sure if the problem about having to ping the bot every 5th minute to keep it alive still exists, as slack-irc doesn't listen to any ports anymore (and thus, maybe it could be deployed to a worker dyno?). However, there's still the problem of the dynos restarting once a day, which is kind of negative for an IRC bot.

If people feel like deploying it to Heroku still works something like the solution you're offering here might be good. Maybe let the input tokens be a comma separated list or something, so it'd still work if you want to run multiple bots. Another option (which used to be available in an earlier slack-irc version) would be to have the whole config input as JSON from an env variable, i.e.
`export SLACK_IRC_CONFIG="{...config goes here...}"`, but that's also kind of an awkward solution.

**Comment by javajax** [comment]
The problem is that our slack irc configuration is in version control and we need a way to keep sensitive data out of the configuration.

**Comment by javajax** [comment]
Heroku was a side comment I just think ENV vars are a good way to handle the sensitive data.

**Comment by ekmartin** [comment]
The config file can be a JS-file too, so if you already have the config in version control, wouldn't something like this be as effective?

```js
module.exports = {
  nickname: 'test',
  server: 'irc.bottest.org',
  token: process.env.SLACK_TOKEN,
  autoSendCommands: [
    ['MODE', 'test', '+x'],
    ['AUTH', 'test', 'password']
  ],
  channelMapping: {
    '#slack': '#irc channelKey'
  }
};
```

**Comment by javajax** [comment]
That should work for our use case.
It still might be a good idea to do env configuration for sensitive data though.  We are currently implementing a work around but I might switch to this.

**Comment by ekmartin** [comment]
> It still might be a good idea to do env configuration for sensitive data though. 

I might be misunderstanding, but isn't that exactly what using `process.env.SLACK_TOKEN` in a JS configuration file does?

**Pull request closed without merging**
