### PR TITLE
fix highlight problem with common usernames

### PR DESCRIPTION
**Pull request by narula**
Very hacky attempt at not highlighting four common english words just because someone in the slack has selected one of them as a username.

### CODE REVIEW

**Comment by narula** [comment]
I am happy to do this in a more robust way if you can point me in the right direction!

**Comment by ekmartin** [comment]
Hi! Did you see the comments over at #132?
I think there's a few options here:
* Allow the common words to be configured with an array from the config.
* Add a JSON file with something like the 100 most common words (i.e. https://github.com/jonschlinkert/common-words or similar), and use that to know which usernames to ignore.
* Add an option to disable the feature altogether, i.e. don't append `@` to usernames.

For large channels I think the last one might be better, as users could still highlight people with `@` manually, but I'm not sure. Between the first two I think I'd prefer the second, as I still feel like it's a bit of a painful thing to configure.

What do you think?

**Comment by btcdrak** [comment]
I would actually take 1 and 3 as it gives power to the bot administrator. I'd have no problem with adding the odd word or two to an array. The problem with option 2 is you are bound to get the odd user complain they cant blacklist something not in the top100list and that would be a maintenance nightmare.

**Comment by ekmartin** [comment]
Hi! I'm gonna close this, as I think one of the suggested approaches above is a better direction to go. If you or anyone else want to send a pull request I'd be happy to discuss in slack-irc's [Gitter](https://gitter.im/ekmartin/slack-irc)!

**Pull request closed without merging**
