### PR TITLE
Slack image to Imgur upload + IRC<->Slack "private" chat

### PR DESCRIPTION
**Pull request by hipio**
**Warning**: This feature request should not be merged. It should be looked at and incorporated. You could merge it, but it's a bit messy and needs a clean up.

This PR adds two important functions:
- Images uploaded on Slack will be uploaded to Imgur and the link will be shared on IRC
- You can now send messages through the bot to IRC- or Slack users. 

Again, the code is not very clean. It was a quick solution to what I felt was missing in this bot.

### CODE REVIEW

**Comment by hipio** [comment]
Oh boy. The CI's are killing my PR because of linting issues. Should have used an editor that played nice, but well, I didn't mean to create a PR for this. 

Uuuh, if you want, I can update the code to fix the issues.

**Comment by ekmartin** [comment]
This is definitely cool, but I'm not sure if it needs to be a part of the core functionality. I'm gonna forward people to your fork for now, but if enough people find it useful I'll reconsider. Hope that's okay!

**Comment by duramato** [comment]
Just leaving my opinion, this is definitly something i would like to see. There are many times i miss images becouse they aren't releayed.

**Comment by hipio** [comment]
@ekmartin Well, if you want feedback from people, wouldn't it be easier to leave the PR open so it's easily seen by others. Just tag it with "need-feedback-from-community" or something. 

@duramato That's the whole reason I made this change. I was missing a lot of pictures on IRC because it doesn't get relayed.

**Comment by duramato** [comment]
@ekmartin sorry to relive this, but has any further consideration has been put in to this? This is a feature i'm really missing. It doesn't necessarly need to be uploading to imgur, it can even be just the releay of the original image link slack gives, altough idk if it would work.

**Pull request closed without merging**
